language: java
jdk: oraclejdk8

env:
  global:
  - secure: "bdff98e6ccecb9072790807739d0f7fa6eff3ea4"

addons:
  sonarcloud:
    organization: "lehauchicha-github"
    token:
      secure: $SONAR_TOKEN

script:
- ./mvnw clean install -B
- ./mvnw sonar:sonar
      -Dsonar.projectKey=LehaUchicha_blog-server
      -Dsonar.organization=lehauchicha-github
      -Dsonar.host.url=https://sonarcloud.io
      -Dsonar.login=bdff98e6ccecb9072790807739d0f7fa6eff3ea4