language: java
jdk: oraclejdk8

env:
  global:
  - secure: "bdff98e6ccecb9072790807739d0f7fa6eff3ea4"

addons:
  sonarcloud:
    organization: "lehauchicha-github"
    token:
      secure: $SONAR_TOKEN

script:
- ./mvnw clean install -B
- ./mvnw sonar:sonar
      -Dsonar.projectKey=LehaUchicha_blog-server
      -Dsonar.organization=lehauchicha-github
      -Dsonar.host.url=https://sonarcloud.io
      -Dsonar.login=bdff98e6ccecb9072790807739d0f7fa6eff3ea4

sudo: required

services:
  - docker

before_install:
  - docker pull lehauchiha/blog-server
  - docker run -d -p 127.0.0.1:80:4567 lehauchiha/blog-server /bin/sh -c "cd /root/lehauchiha; bundle exec foreman start;"
  - docker ps -a
  - docker run lehauchiha/blog-server /bin/sh -c "cd /root/lehauchiha; bundle exec rake test"

script:
  - bundle exec rake test